//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// BOKOPad.rc에서 사용되고 있습니다.
//
#define IDR_MAINFRAME                   5
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_BOKOPAD_DIALOG              102
#define IDD_DIALOG_OPTION               131
#define IDD_DIALOG_OPTION_EXPORT        133
#define IDD_DIALOG_SCENARIO_TIMELINE    135
#define IDD_DIALOG_NOTE_LIST_CTRL       137
#define IDD_DIALOG_DRAG_DIALOG          139
#define IDD_DIALOG_TIMELINE             141
#define IDD_DIALOG_TIMELINE_DETAIL      143
#define IDD_DIALOG_TIMELINE_ONE_VIEW    147
#define IDD_DIALOG_ONE_VIEW_LIST        149
#define IDR_MENU_MAIN                   153
#define IDD_DIALOG_LOG_VIEW             154
#define IDD_DIALOG_PROGRESS_POPUP       156
#define IDB_PNG_EXCEL                   158
#define IDB_PNG_NOTEPAD                 159
#define IDB_PNG_WORD                    160
#define IDD_DIALOG_SELECT_EXPORT_TIMELINE_EXTENTION 161
#define IDB_PNG_ICON                    165
#define IDB_PNG_ICON2                   166
#define IDB_PNG_BK_BOTTOM               167
#define IDB_PNG_BK_LEFT                 168
#define IDB_PNG_BK_RIGHT                169
#define IDB_PNG_BK_TITLE                170
#define IDD_DIALOG_MENU                 171
#define IDB_PNG_BK_SUB                  173
#define IDB_PNG_BK                      174
#define IDD_DIALOG_SCROLL_BAR           175
#define IDD_DIALOG_EDIT                 178
#define IDD_DIALOG_SCENARIO_LIST_CTRL   180
#define IDB_PNG_NOTE_ADD                194
#define IDD_DIALOG_SCENARIO_ADD         196
#define IDB_PNG_NOTE_BLACK              199
#define IDB_PNG_NOTE_BLUE               200
#define IDB_PNG_NOTE_BROWN              201
#define IDB_PNG_NOTE_GREEN              202
#define IDB_PNG_NOTE_ORANGE             203
#define IDB_PNG_NOTE_PINK               204
#define IDB_PNG_NOTE_PURPLE             205
#define IDB_PNG_NOTE_RED                206
#define IDB_PNG_NOTE_SKY                207
#define IDB_PNG_NOTE_TABLE              208
#define IDB_PNG_NOTE_YELLOW             209
#define IDB_PNG1                        210
#define IDB_PNG_BK_LIGHT                210
#define IDC_LIST_SCENARIO_LIST          1000
#define IDC_BUTTON_OPTION               1001
#define IDC_EDIT_INPUT_SCENARIO         1002
#define IDC_BUTTON_INPUT_SCENARIO       1003
#define IDC_BUTTON_SCENARIO_TITLE_MODIFY 1005
#define IDC_BUTTON_SCENARIO_DELETE      1006
#define IDC_RADIO_TEST1                 1007
#define IDC_RADIO_TEST2                 1008
#define IDC_BUTTON_EXPORT_FILE          1011
#define IDC_BUTTON_IMPORT_FILE          1012
#define IDC_LIST_OPTION_SELECT_SCENARIO 1013
#define IDC_EDIT_NOTE_INPUT             1014
#define IDC_BUTTON_NOTE_INPUT           1015
#define IDC_STATIC_NOTE_LIMIT_SIZE      1016
#define IDC_EDIT_DRAG_EDIT              1017
#define IDC_STATIC_DRAG_STATIC          1018
#define IDC_EDIT_TIMELINE_DETAIL_THIS   1019
#define IDC_EDIT_TIMELINE_DETAIL_TARGET 1020
#define IDC_EDIT_TIMELINE_ONE_VIEW_EDIT 1024
#define IDC_BUTTON_TIMELINE_EXPORT      1025
#define IDC_CHECK_DRAG_MODE             1028
#define IDC_BUTTON_NOTE_DELETE          1030
#define IDC_BUTTON_ONE_VIEW             1031
#define IDC_BUTTON_EXPAND_ALL           1032
#define IDC_LIST_LOG_VIEW               1034
#define IDC_COMBO_LOG_DIVIDE            1035
#define IDC_LIST_LOG_COUNT              1036
#define IDC_DATETIMEPICKER_CURRENT_DATE 1037
#define IDC_DATETIMEPICKER_LAST_DATE    1038
#define IDC_BUTTON_EXECUTE_LOG          1039
#define IDC_PROGRESS_STATUS             1040
#define IDC_STATIC_PROGRESS_FILE_NAME   1041
#define IDC_BUTTON_SELECT_NOTEPAD       1042
#define IDC_BUTTON_SELECT_WORD          1043
#define IDC_BUTTON_SELECT_EXCEL         1044
#define IDC_MFCBUTTON_NOTEPAD           1045
#define IDC_MFCBUTTON_EXCEL             1046
#define IDC_MFCBUTTON_WORD              1047
#define IDC_STATIC_TIMELINE_COUNT       1049
#define IDC_PROGRESS_TIMELINE_COUNT     1050
#define IDC_MFCBUTTON_TOP               1051
#define IDC_MFCBUTTON_BOTTOM            1053
#define IDC_MFCBUTTON_MIDDLE            1054
#define IDC_EDIT_CUSTOM                 1055
#define IDC_MFCBUTTON_ADD_ITEM          1056
#define IDC_MFCBUTTON_SCENARIO_ADD      1057
#define IDC_STATIC_SCENARIO             1058
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_32773                        32773
#define ID_32774                        32774
#define ID_32775                        32775
#define ID_32776                        32776
#define ID_SCENARIO_EXPORT              32777
#define ID_SCENARIO_IMPORT              32778
#define ID_PROGRAM_CLOSE                32779
#define ID_LOG_VIEW                     32780
#define ID_32781                        32781
#define ID_EXPLANATION_VIEW             32782

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        211
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         1059
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
